spring:
  application:
    name: mapa-acessibilidade-api

  datasource:
    url: jdbc:postgresql://prod-db:5432/prod_db
    username: prod_user
    password: prod_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true

  mvc:
    servlet:
      path: /mapa-acessibilidade/api

  logging:
    level:
      root: WARN

  cors:
    frontend:
      origin: http://localhost:4200/