name: CI with Maven and Liquibase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -Pprod

      - name: Run Liquibase migration (produção)
        run: |
          mvn liquibase:update \
            -Pprod \
            -Dliquibase.url="${{ secrets.DB_URL }}" \
            -Dliquibase.username="${{ secrets.DB_USER }}" \
            -Dliquibase.password="${{ secrets.DB_PASS }}" \
            -Dliquibase.driver=org.postgresql.Driver \
            -Dliquibase.changeLogFile=src/main/resources/db/changelog/changelog-master.xml

      - name: Build Docker image
        run: docker build -t mapa-acessibilidade .

    env:
      CORS_ORIGIN: ${{ vars.CORS_ORIGIN }}